module.exports = {
  space: [0, 4, 8, 16, 24, 32, 48, 64, 96, 128, 256, 512],
  fonts: {
    body:
      'relative-book-pro, Roboto, system-ui, -apple-system, BlinkMacSystemFont',
    faux:
      'relative-faux-book-pro, Roboto, system-ui, -apple-system, BlinkMacSystemFont',
    heading:
      'relative-medium-pro, Roboto, system-ui, -apple-system, BlinkMacSystemFont',
    mono: 'relative-mono-11-pitch-pro, Menlo, monospace',
  },
  fontSizes: [12, 14, 16, 18, 24, 34, 48, 64, 80, 96, 128],
  letterSpacings: {
    body: '0.01em',
    mono: '0.07em',
    faux: '0.05em',
    heading: '-0.015em',
    smallcaps: '0.07em',
  },
  fontWeights: {
    body: 400,
    heading: 400,
    bold: 400,
  },
  lineHeights: {
    body: 1.35,
    heading: 1.05,
    h1: 1.05,
    h2: 1.1,
    h3: 1.2,
  },
  colors: {
    text: '#ebebec',
    background: '#1b1e23',
    primary: '#ebebec',
    secondary: '#808080',
    muted: '#393a3d',
    red: '#f07071',
    orange: '#ea9755',
    yellow: '#d4c05e',
    green: '#7eb36a',
    teal: '#64b9c4',
    blue: '#85a2f7',
    purple: '#bc85d9',
    pink: '#e587b6',
    grey: '#a9b4c4',
    modes: {
      light: {
        text: '#1b1e23',
        background: '#FFFFFF',
        primary: '#1b1e23',
        secondary: '#808080',
        muted: '#b9b9bb',
        red: '#f07071',
        orange: '#ea9755',
        yellow: '#d4c05e',
        green: '#7eb36a',
        teal: '#64b9c4',
        blue: '#85a2f7',
        purple: '#bc85d9',
        pink: '#e587b6',
        grey: '#a9b4c4',
      },
    },
  },
  layout: {
    container: {
      px: [3, 4, 5, 6],
      maxWidth: '1920px',
    },
  },
  text: {
    paragraph: {
      fontSize: [3],
      fontFamily: 'body',
      lineHeight: 'body',
      fontWeight: 'body',
      letterSpacing: 'body',
      my: ['1em'],
    },
  },
  styles: {
    root: {
      fontFamily: 'body',
      lineHeight: 'body',
      fontWeight: 'body',
      letterSpacing: 'body',
    },
    a: {
      color: 'text',
      '&:active': {
        color: 'text',
      },
      '&:hover': {
        color: 'secondary',
      },
      textDecoration: 'underline',
      cursor: 'pointer',
    },
    hr: {
      border: 'none',
      borderStyle: 'solid',
      borderWidth: '0px',
      borderTopWidth: '1px',
      borderColor: 'muted',
    },
    p: {
      fontSize: [3, 3, 3, 4],
      lineHeight: 'body',
      fontFamily: 'body',
      fontWeight: 'body',
      letterSpacing: 'body',
      my: ['1em'],
    },
    h1: {
      fontSize: [6, 6, 7, 8],
      fontFamily: 'heading',
      letterSpacing: 'heading',
      fontWeight: 'heading',
      lineHeight: 'h1',
      mt: [5, 7, 7],
      mb: [5, 6, 6],
    },
    h2: {
      fontSize: [5, 5, 5, 6],
      fontFamily: 'heading',
      fontWeight: 'heading',
      lineHeight: 'h2',
      mt: [5, 6, 6],
      mb: [4, 5, 5],
    },
    h3: {
      fontSize: [4, 4, 4, 5],
      fontFamily: 'heading',
      fontWeight: 'heading',
      lineHeight: 'h3',
      mt: [4, 5, 5],
      mb: [3, 4, 4],
    },
  },
  breakpoints: ['40em', '64em', '102em'],
  useColorSchemeMediaQuery: false,
}
